### ISSUE TITLE
TaggingExtra#count_tags(item=nil) if items not nil

### ISSUE THREAD

**Issue by kfl62** [mgutz/nanoc3_blog#2]
Should be
    def count_tags(items=nil)
      items = @items if items.nil?
      count = Hash.new( 0 )
      #@items.each do |item| # not working
        items.each do |item|
        if item[:tags]
          item[:tags].each do |tag|
            count[ tag ] += 1
          end
        end
      end
      count
    end

in current format ignores items passed as parameter

**Comment by mgutz** [comment]
thanks for reporting, will take a look and fix soon
