### ISSUE TITLE
Can't modify frozen hash

### ISSUE THREAD

**Issue by iflowfor8hours** [mgutz/nanoc3_blog#5]
Not sure what to do about this at the moment, but working on it. I believe it has something to do with the way you are printing dates in articles.

Running on http://0.0.0.0:3000/
[2011-08-22 17:02:00] INFO  WEBrick 1.3.1
[2011-08-22 17:02:00] INFO  ruby 1.9.2 (2011-02-18) [x86_64-linux]
[2011-08-22 17:02:00] INFO  WEBrick::HTTPServer#start: pid=20318 port=3000
RuntimeError: can't modify frozen hash
    layout /default/:2:in `[]='
    layout /default/:2:in`block in render'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/haml-3.1.2/lib/haml/engine.rb:191:in `eval'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/haml-3.1.2/lib/haml/engine.rb:191:in`render'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/filters/haml.rb:23:in `run'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/result_data/item_rep.rb:400:in`layout'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/item_rep_proxy.rb:68:in `layout'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/rule_context.rb:67:in`layout'
    ./Rules:34:in `block in load'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/rule.rb:68:in`instance_eval'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/rule.rb:68:in `apply_to'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/compiler.rb:377:in`compile_rep'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/compiler.rb:333:in `block in compile_reps'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/compiler.rb:326:in`loop'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/compiler.rb:326:in `compile_reps'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/compiler.rb:85:in`run'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/source_data/site.rb:57:in `compile'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/extra/auto_compiler.rb:48:in`block in call'
    internal:prelude:10:in `synchronize'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/extra/auto_compiler.rb:35:in`call'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.2/lib/rack/showexceptions.rb:24:in `call'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.2/lib/rack/commonlogger.rb:20:in`call'
    /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.2/lib/rack/handler/webrick.rb:59:in `service'
    /home/matt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/httpserver.rb:111:in`service'
    /home/matt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
    /home/matt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/server.rb:183:in`block in start_thread'
127.0.0.1 - - [22/Aug/2011 17:02:10] "GET / HTTP/1.1" 500 67130 1.0042
localhost.localdomain - - [22/Aug/2011:17:02:09 EDT] "GET / HTTP/1.1" 500 67130
- -> /
  127.0.0.1 - - [22/Aug/2011 17:02:11] "GET /favicon.ico HTTP/1.1" 404 29 0.0942
  localhost.localdomain - - [22/Aug/2011:17:02:11 EDT] "GET /favicon.ico HTTP/1.1" 404 29
- -> /favicon.ico
  RuntimeError: can't modify frozen hash
  layout /default/:2:in `[]='
  layout /default/:2:in`block in render'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/haml-3.1.2/lib/haml/engine.rb:191:in `eval'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/haml-3.1.2/lib/haml/engine.rb:191:in`render'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/filters/haml.rb:23:in `run'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/result_data/item_rep.rb:400:in`layout'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/item_rep_proxy.rb:68:in `layout'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/rule_context.rb:67:in`layout'
  ./Rules:34:in `block in load'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/rule.rb:68:in`instance_eval'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/rule.rb:68:in `apply_to'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/compiler.rb:377:in`compile_rep'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/compiler.rb:333:in `block in compile_reps'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/compiler.rb:326:in`loop'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/compiler.rb:326:in `compile_reps'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/compilation/compiler.rb:85:in`run'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/base/source_data/site.rb:57:in `compile'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/extra/auto_compiler.rb:48:in`block in call'
  internal:prelude:10:in `synchronize'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/nanoc3-3.2.1/lib/nanoc3/extra/auto_compiler.rb:35:in`call'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.2/lib/rack/showexceptions.rb:24:in `call'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.2/lib/rack/commonlogger.rb:20:in`call'
  /home/matt/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.2/lib/rack/handler/webrick.rb:59:in `service'
  /home/matt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/httpserver.rb:111:in`service'
  /home/matt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
  /home/matt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/server.rb:183:in`block in start_thread'
  127.0.0.1 - - [22/Aug/2011 17:02:13] "GET / HTTP/1.1" 500 67130 0.2504
  localhost.localdomain - - [22/Aug/2011:17:02:12 EDT] "GET / HTTP/1.1" 500 67130
- -> /
  127.0.0.1 - - [22/Aug/2011 17:02:13] "GET /favicon.ico HTTP/1.1" 404 29 0.0641
  localhost.localdomain - - [22/Aug/2011:17:02:13 EDT] "GET /favicon.ico HTTP/1.1" 404 29
- -> /favicon.ico

**Comment by pcalcado** [comment]
Same problem here after moving to new machine and reinstalling ruby env from scratch. Did you get anywhere?

Cheers

**Comment by iflowfor8hours** [comment]
nope, no luck for me either. i moved my blog to something I wrote myself. Oh
well.

2011/10/8 Phil Calado <
reply@reply.github.com>

**Comment by pcalcado** [comment]
I fixed my issue with a hack, not sure what could be broken after this but so far everything works:

--- a/layouts/_meta.haml
+++ b/layouts/_meta.haml
@@ -5,7 +5,6 @@
     %ul.tags
       %li= pretty_time(item[:created_at])
       - if disqus_shortname 
-        - @config[:include_disqus_js] = true
       %li
         &middot;
       %li
  diff --git a/layouts/default.haml b/layouts/default.haml
  index 09eee83..b59f579 100644
  --- a/layouts/default.haml
  +++ b/layouts/default.haml
  @@ -2,7 +2,7 @@
  ---
  :ruby
   # may be set by partials
-  @config[:include_disqus_js] = false
-  #@config[:include_disqus_js] = false
  
  def keywords
   if is_front_page?
